DROP TABLE IF EXISTS tipocambio;
CREATE TABLE tipocambio (
 id int generated by default as identity (start with 1) primary key,
 estado int(2)DEFAULT NULL,
 tipo VARCHAR(250)   DEFAULT NULL,
 valor DOUBLE DEFAULT NULL);


